[tool.poetry]
name = "anatooly"
version = "0.1.0"
description = "Tool for analyzing architecture and tech stack detection"

packages = [
  { include = "anatooly", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.scripts]
anatooly = "anatooly.cli:main"
